# -*- coding: utf-8 -*-
"""backtest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j1ulHELQij_7qMXN_QJ8CIxuhFj_3Lnv
"""

def backtest(df):
    buy_price = None
    trades = []

    for i in range(len(df)):
        # Safely get the Buy_Signal value
        signal = df['Buy_Signal'].iloc[i]
        rsi = df['RSI'].iloc[i]
        close_price = df['Close'].iloc[i]
        date = df.index[i]

        # Ensure signal is a scalar boolean
        if bool(signal) and buy_price is None:
            buy_price = close_price
            trades.append({'Date': date, 'Action': 'Buy', 'Price': buy_price})

        elif buy_price is not None and rsi > 70:
            sell_price = close_price
            trades.append({'Date': date, 'Action': 'Sell', 'Price': sell_price, 'P&L': sell_price - buy_price})
            buy_price = None

    return trades