# -*- coding: utf-8 -*-
"""data_fetch.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RdhRgkgpcJLrHbcvGa0bQagEXjemdobl
"""

import yfinance as yf
import pandas as pd

def fetch_stock_data(stock_list, start, end):
    data_dict = {}
    for stock in stock_list:
        df = yf.download(stock, start=start, end=end)
        df.dropna(inplace=True)
        data_dict[stock] = df
    return data_dict