# -*- coding: utf-8 -*-
"""google_sheet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BKxllQdN8ukelFu98KidQRSQfWV3LwSH
"""

import gspread
from google.oauth2.service_account import Credentials
import os

def connect_google_sheet(sheet_name):
    scope = [
        "https://www.googleapis.com/auth/spreadsheets",
        "https://www.googleapis.com/auth/drive"
    ]
    creds_path = os.getenv("GOOGLE_SHEETS_CREDENTIALS")
    creds = Credentials.from_service_account_file(creds_path, scopes=scope)
    client = gspread.authorize(creds)
    sheet = client.open(sheet_name)

    # Ensure "Trade Log" worksheet exists
    try:
        sheet.worksheet("Trade Log")
    except gspread.WorksheetNotFound:
        sheet.add_worksheet(title="Trade Log", rows="100", cols="5")

    return sheet

def log_trades(sheet, trades):
    worksheet = sheet.worksheet("Trade Log")
    for trade in trades:
        worksheet.append_row([str(trade['Date']), trade['Action'], trade['Price'], trade.get('P&L', '')])