# -*- coding: utf-8 -*-
"""strategy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOiu2qJ-19nd5khqWFa2pWK339Kkad3u
"""

import pandas as pd

def compute_rsi(close, period=14):
    delta = close.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.rolling(window=period).mean()
    avg_loss = loss.rolling(window=period).mean()

    rs = avg_gain / avg_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def apply_strategy(df):
    df['RSI'] = compute_rsi(df['Close'], 14)
    df['20_MA'] = df['Close'].rolling(window=20).mean()
    df['50_MA'] = df['Close'].rolling(window=50).mean()
    df['Buy_Signal'] = (df['RSI'] < 30) & (df['20_MA'] > df['50_MA'])
    return df