# -*- coding: utf-8 -*-
"""telegram_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vUK1kCk8XJRL5OfFNWYe0HoD9N5XFZ6H
"""

import os
import requests

def send_telegram(message):
    token = os.getenv("TELEGRAM_TOKEN")
    chat_id = os.getenv("TELEGRAM_CHAT_ID")

    # Debug log
    if not token or not chat_id:
        print("Telegram alert skipped: missing token or chat ID.")
        print(f"TOKEN: {token}, CHAT_ID: {chat_id}")
        return
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = {"chat_id": chat_id, "text": message}

    try:
        response = requests.post(url, data=payload)
        if response.status_code != 200:
            print(f"Telegram alert failed: {response.status_code} - {response.text}")
        else:
            print("✅ Telegram alert sent!")
    except Exception as e:
        print(f"Telegram alert error: {e}")